### ISSUE TITLE
Cannot convert .pb to .nn using tensorflow_to_barracuda.py

### ISSUE THREAD

**Issue by devich123** [Unity-Technologies/barracuda-release#71]
I am trying to convert a custom trained tensorflow model on ssd_mobilenet_v1_coco to .nn format to use in Unity. I have tried tensorflow_to_barracuda.py code with both frozen_inference_graph.pb and saved_model.pb files and these are the errors I got. I have searched for a solution but didn't find any. Please help me. @mantasp @xiaomaogy

When converting saved_model.pb

```
Traceback (most recent call last):
File "barracuda-release-release-1.0.0/Tools/tensorflow_to_barracuda.py", line 21, in
tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
File "C:\Users\Devi\devi\tensorflow\models\research\object_detection\inference_graph-cpu-1.14\barracuda-release-release-1.0.0\Tools\tensorflow_to_barracuda.py", line 1351, in convert
i_model.ParseFromString(f.read())
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
return self.MergeFromString(serialized)
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\python_message.py", line 1134, in MergeFromString
if self._InternalParse(serialized, 0, length) != length:
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\python_message.py", line 1201, in InternalParse
pos = field_decoder(buffer, new_pos, end, self, field_dict)
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\decoder.py", line 738, in DecodeField
if value._InternalParse(buffer, pos, new_pos) != new_pos:
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\python_message.py", line 1201, in InternalParse
pos = field_decoder(buffer, new_pos, end, self, field_dict)
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\decoder.py", line 717, in DecodeRepeatedField
if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\python_message.py", line 1201, in InternalParse
pos = field_decoder(buffer, new_pos, end, self, field_dict)
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\decoder.py", line 872, in DecodeMap
if submsg._InternalParse(buffer, pos, new_pos) != new_pos:
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\python_message.py", line 1188, in InternalParse
buffer, new_pos, wire_type) # pylint: disable=protected-access
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\decoder.py", line 973, in _DecodeUnknownField
(data, pos) = _DecodeUnknownFieldSet(buffer, pos)
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\decoder.py", line 952, in _DecodeUnknownFieldSet
(data, pos) = _DecodeUnknownField(buffer, pos, wire_type)
File "C:\Users\Devi.conda\envs\tensorflow1\lib\site-packages\google\protobuf\internal\decoder.py", line 977, in _DecodeUnknownField
raise _DecodeError('Wrong wire type in tag.')
google.protobuf.message.DecodeError: Wrong wire type in tag.
```

When converting frozen_inference_graph.pb

```
Sorting model, may take a while................................... Done!
IGNORED: Cast unknown layer
IGNORED: Shape unknown layer
IGNORED: TensorArrayV3 unknown layer
IGNORED: Shape unknown layer
IGNORED: Range unknown layer
IGNORED: TensorArrayScatterV3 unknown layer
IGNORED: TensorArrayV3 unknown layer
IGNORED: TensorArrayV3 unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
WARNING: rank unknown for tensor Preprocessor/map/while/Switch:1 while processing node Preprocessor/map/while/Identity
Traceback (most recent call last):
File "barracuda-release-release-1.0.0/Tools/tensorflow_to_barracuda.py", line 21, in
tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
File "C:\Users\Devi\devi\tensorflow\models\research\object_detection\inference_graph-cpu-1.14\barracuda-release-release-1.0.0\Tools\tensorflow_to_barracuda.py", line 1364, in convert
process_model(i_model, args)
File "C:\Users\Devi\devi\tensorflow\models\research\object_detection\inference_graph-cpu-1.14\barracuda-release-release-1.0.0\Tools\tensorflow_to_barracuda.py", line 1226, in process_model
process_layer(node, o_context, args)
File "C:\Users\Devi\devi\tensorflow\models\research\object_detection\inference_graph-cpu-1.14\barracuda-release-release-1.0.0\Tools\tensorflow_to_barracuda.py", line 1095, in process_layer
assert(-1 not in input_ranks) # for rank() lambda all input ranks have to be known (not -1)
AssertionError

```
To Reproduce

- Activated tensorflow environment
- Cloned barracuda repo from https://github.com/Unity-Technologies/barracuda-release
- Tried converting TF model file using tensorflow_to_barracuda.py
- Command used: python barracuda-release-release-1.0.0/Tools/tensorflow_to_barracuda.py saved_model/saved_model saved_model/saved_model.nn

Unity Version: 2019.4.1f1
OS + version: Windows 10
ML-Agents version: 1.0.2
TensorFlow version: 1.14

**Comment by mantasp** [comment]
@devich123 we are deprecating `tensorflow_to_barracuda.py` support and now the best way to import TF model is by converting it to ONNX and placing ONNX model directly into your Unity project.
Though I noticed you are trying to convert SSD model, which we don't support yet, but it's something we are working right now (still it will require ONNX model).

For object detection YOLO v2/v2tiny works the best at the moment with Barracuda.

**Comment by devich123** [comment]
Hey @mantasp  I even tried to import the ONNX file to Unity. But I got this error.

when importing frozen inference graph.onnx

```
Asset import failed, "Assets/MODEL.frozen.onnx" > OnnxImportException: Unexpected error while parsing layer copy__19/Preprocessor/map/while/LogicalAnd:0 of type And.
An item with the same key has already been added. Key: copy__19/Preprocessor/map/while/Less_1:0

Json: { "input": [ "copy__19/Preprocessor/map/while/Less_1:0", "copy__19/Preprocessor/map/while/Less_1:0" ], "output": [ "copy__19/Preprocessor/map/while/LogicalAnd:0" ], "name": "copy__19/Preprocessor/map/while/LogicalAnd", "opType": "And" }
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
  at Unity.Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes, System.Collections.Generic.IDictionary`2[System.String,System.Nullable`1[Unity.Barracuda.TensorShape]]& shapesByName) [0x000db] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\ModelAnalyzer.cs:92 
  at Unity.Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) [0x00001] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\ModelAnalyzer.cs:66 
  at Unity.Barracuda.ModelAnalyzer.FindLargestNecessaryTensorShape (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) [0x0000c] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\ModelAnalyzer.cs:532 
  at Unity.Barracuda.GenericVarsWithPreallocation.PrepareStorage (Unity.Barracuda.Model model, Unity.Barracuda.IOps ops, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) [0x00023] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\GenericWorker.cs:1125 
  at Unity.Barracuda.GenericWorker+<StartManualSchedule>d__29.MoveNext () [0x0003f] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\GenericWorker.cs:163 
  at Unity.Barracuda.GenericWorker.Execute () [0x0000c] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\GenericWorker.cs:118 
  at Unity.Barracuda.ONNXModelImporter.BakeNodeIntoConstant (System.Action`2[T1,T2] opImportAction, Unity.Barracuda.ONNXNodeWrapper node) [0x0008a] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Editor\ONNXModelImporter.cs:1177 
  at Unity.Barracuda.ONNXModelImporter.ConvertOnnxModel (Onnx.ModelProto onnxModel) [0x002e3] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Editor\ONNXModelImporter.cs:1074 

Unity.Barracuda.ONNXModelImporter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Editor/ONNXModelImporter.cs:1399)
Unity.Barracuda.ONNXModelImporter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Editor/ONNXModelImporter.cs:1092)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Editor/ONNXModelImporter.cs:1000)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <a0a9ad37e16b4f7cb955e1101b72d4cc>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

```

when importing saved_model.onnx
```

Asset import failed, "Assets/MODEL 1.onnx" > OnnxImportException: Unexpected error while parsing layer MultipleGridAnchorGenerator/truediv_10:0 of type Div.
An item with the same key has already been added. Key: Postprocessor/scale_logits/y:0

Json: { "input": [ "Postprocessor/scale_logits/y:0", "Postprocessor/scale_logits/y:0" ], "output": [ "MultipleGridAnchorGenerator/truediv_10:0" ], "name": "MultipleGridAnchorGenerator/truediv_10", "opType": "Div" }
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
  at Unity.Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes, System.Collections.Generic.IDictionary`2[System.String,System.Nullable`1[Unity.Barracuda.TensorShape]]& shapesByName) [0x000db] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\ModelAnalyzer.cs:92 
  at Unity.Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) [0x00001] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\ModelAnalyzer.cs:66 
  at Unity.Barracuda.ModelAnalyzer.FindLargestNecessaryTensorShape (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) [0x0000c] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\ModelAnalyzer.cs:532 
  at Unity.Barracuda.GenericVarsWithPreallocation.PrepareStorage (Unity.Barracuda.Model model, Unity.Barracuda.IOps ops, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) [0x00023] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\GenericWorker.cs:1125 
  at Unity.Barracuda.GenericWorker+<StartManualSchedule>d__29.MoveNext () [0x0003f] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\GenericWorker.cs:163 
  at Unity.Barracuda.GenericWorker.Execute () [0x0000c] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Runtime\Core\Backends\GenericWorker.cs:118 
  at Unity.Barracuda.ONNXModelImporter.BakeNodeIntoConstant (System.Action`2[T1,T2] opImportAction, Unity.Barracuda.ONNXNodeWrapper node) [0x0008a] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Editor\ONNXModelImporter.cs:1177 
  at Unity.Barracuda.ONNXModelImporter.ConvertOnnxModel (Onnx.ModelProto onnxModel) [0x002e3] in C:\Users\Devi\devi\Unity\1\Library\PackageCache\com.unity.barracuda@1.0.0\Barracuda\Editor\ONNXModelImporter.cs:1074 

Unity.Barracuda.ONNXModelImporter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Editor/ONNXModelImporter.cs:1399)
Unity.Barracuda.ONNXModelImporter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Editor/ONNXModelImporter.cs:1092)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.0.0/Barracuda/Editor/ONNXModelImporter.cs:1000)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <a0a9ad37e16b4f7cb955e1101b72d4cc>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by devich123** [comment]
> 
> 
> @devich123 we are deprecating `tensorflow_to_barracuda.py` support and now the best way to import TF model is by converting it to ONNX and placing ONNX model directly into your Unity project.
> Though I noticed you are trying to convert SSD model, which we don't support yet, but it's something we are working right now (still it will require ONNX model).
> 
> For object detection YOLO v2/v2tiny works the best at the moment with Barracuda.

Does anything in Tensorflow works like maybe Faster RCNN or some other model ??

**Comment by AlexRibard** [comment]
Hi @devich123 
You can checkout this guide on how to export a model from TF to ONNX and into Barracuda
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Exporting.md
Here is the operators we support at the moment
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/SupportedOperators.md

With SSD there are two main problematic nodes TopK and NonMaxSuppression. So our workaround atm (until we finish our support for SSD) is to cut out the end part of the model and implement that in C# directly.
Faster RCNN is the same. The start of the model is fine, but the BBOX handling is the problem atm.

Note that SSD support is our top priority atm and we'll notify you when we push the support for them :)

**Comment by devich123** [comment]
> 
> 
> Hi @devich123
> You can checkout this guide on how to export a model from TF to ONNX and into Barracuda
> https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/Exporting.md
> Here is the operators we support at the moment
> https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/SupportedOperators.md
> 
> With SSD there are two main problematic nodes TopK and NonMaxSuppression. So our workaround atm (until we finish our support for SSD) is to cut out the end part of the model and implement that in C# directly.
> Faster RCNN is the same. The start of the model is fine, but the BBOX handling is the problem atm.
> 
> Note that SSD support is our top priority atm and we'll notify you when we push the support for them :)

Thank you so much.
